### ISSUE TITLE
Getting errors with the test script. 

### ISSUE THREAD

**Issue by daninger4995** [bonehurtingjuice/mattereddit#1]
I ran the install and all the node modules are installed, so I'm not sure why this error is popping up.

`Lifecycle scripts included in mattereddit:`

`  test`

    `echo "Error: no test specified" && exit 1
`

**Comment by DeclanHoare** [comment]
That's just hardcoded in to the package.json, I think it's a default value from node itself.  This package doesn't have a test.

**Comment by daninger4995** [comment]
I ended up getting it working by just installing chromium with apt-get. It seems to be an issue with that. Now I am just trying to get it working to listen to the chatrooms, although it says it's connected to Reddit so I have a feeling the issue is on reddits end.

**Comment by DeclanHoare** [comment]
It might not work anymore, I haven't used it in a long time and it's a fragile scraper.  Although, reddit's chat doesn't seem to have changed much either.

**Comment by daninger4995** [comment]
Yea, I think it's an issue with reddit chat making it not work anymore. It would be nice if they provided some API end points for it. Thanks for making this though!
