### ISSUE TITLE
The Script for getting the reddit token has been deleted

### ISSUE THREAD

**Issue by xavierxross** [bonehurtingjuice/mattereddit#5]
This[ gist ](https://raw.githubusercontent.com/scrubjay55/Reddit_ChatBot_Python/master/dump_access_token/dump_access_token.py)has been deleted most probably ig. Opening the gist is showing [this ](https://raw.githubusercontent.com/scrubjay55/Reddit_ChatBot_Python/master/dump_access_token/dump_access_token.py)

**Comment by DeclanHoare** [comment]
Reddit Community Chat has shut down so this won't work anymore.

**Comment by xavierxross** [comment]
LMAO
I wasn't aware

**Comment by j-hc** [comment]
I found a better way (without parsing any html) to obtain fully scoped access token btw. If anybody still needs it it's here https://github.com/scrubjay55/Reddit_ChatBot_Python/blob/master/Reddit_ChatBot_Python/RedditAuthentication.py
